In [332]:
import numpy as np

In [333]:
class Matrix():
    
    def __init__(self, list_of_list):
        
        self.arr = np.array(list_of_list)
        
    def print_matrix(self):
        
        print(self.arr)
        
    def trans_matrix(self):
        
        return self.arr.T
    
    def plus_matrix(self, matrix):

        return self.arr + matrix.arr
    
    def minus_matrix(self, matrix):

        return self.arr - matrix.arr
    
    def mlt_matrix_by_number(self, number):
        
        return self.arr * number
    
    def mlt_matrix_by_matrix(self, matrix):
        
        return self.arr * matrix.trans_matrix()
    
    def dvs_matrix_by_number(self, number):
        
        return self.arr / number

In [334]:
a = [[4, 2, 0], [1, 3, 2], [-1, 3, 10]]
A = Matrix(a)
b = [[7, 8, 1], [5, 6, 3], [2, 4, -2]]
B = Matrix(b)

In [335]:
A.print_matrix()
B.print_matrix()

[[ 4  2  0]
 [ 1  3  2]
 [-1  3 10]]
[[ 7  8  1]
 [ 5  6  3]
 [ 2  4 -2]]


In [336]:
print(A.plus_matrix(B))
print(A.minus_matrix(B))

[[11 10  1]
 [ 6  9  5]
 [ 1  7  8]]
[[-3 -6 -1]
 [-4 -3 -1]
 [-3 -1 12]]


In [337]:
print(A.trans_matrix())

[[ 4  1 -1]
 [ 2  3  3]
 [ 0  2 10]]


In [338]:
print(A.mlt_matrix_by_number(4))
print(A.mlt_matrix_by_matrix(B))

[[16  8  0]
 [ 4 12  8]
 [-4 12 40]]
[[ 28  10   0]
 [  8  18   8]
 [ -1   9 -20]]


In [339]:
C = Matrix(A.arr[0, :])
A.arr[0, :], A.arr[1, :] = A.arr[1, :], C.arr
A.print_matrix()

[[ 1  3  2]
 [ 4  2  0]
 [-1  3 10]]


In [340]:
A.arr[1, :] = Matrix(A.arr[1, :]).plus_matrix(Matrix(Matrix(A.arr[0, :]).mlt_matrix_by_number(-4)))
A.arr[2, :] = Matrix(A.arr[2, :]).plus_matrix(Matrix(A.arr[0, :]))
A.print_matrix()

[[  1   3   2]
 [  0 -10  -8]
 [  0   6  12]]


In [341]:
A.arr[1, :] = Matrix(A.arr[1, :]).dvs_matrix_by_number(-2)
A.arr[2, :] = Matrix(A.arr[2, :]).dvs_matrix_by_number(6)
A.print_matrix()

[[1 3 2]
 [0 5 4]
 [0 1 2]]


In [342]:
C = Matrix(A.arr[1, :])
A.arr[1, :], A.arr[2, :] = A.arr[2, :], C.arr
A.print_matrix()

[[1 3 2]
 [0 1 2]
 [0 5 4]]


In [343]:
A.arr[2, :] = Matrix(A.arr[2, :]).plus_matrix(Matrix(Matrix(A.arr[1, :]).mlt_matrix_by_number(-5)))
A.print_matrix()

[[ 1  3  2]
 [ 0  1  2]
 [ 0  0 -6]]
